### ISSUE TITLE
Problems With Using lindamasternodes.js

### ISSUE THREAD

**Issue by coolindark** [nibbles83/LindaExplorer#1]
Hello. Once i try to use lindamasternodes.js, i got this output.
What can cause this issue?

/root/explorer/scripts/lindamasternodes.js:48
                          lib.syncLoop(body.length, function (loop) {
                                           ^

TypeError: Cannot read property 'length' of undefined
    at Request._callback (/root/explorer/scripts/lindamasternodes.js:48:23)
    at self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/root/explorer/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1290:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Thanks.

**Comment by nibbles83** [comment]
Sorry for the late reply on this. Didn't see it come in.

The error above basically means that the array "body.length" is empty.

In all likelihood this is because the API command that is run to get this array content doesn't exist in the standard version of the Linda wallet. You can test this by running from your command line:

`Lindad masternode status-all`

If you get an error about a non existent command then that's the issue.

You will need to compile my custom Linda wallet in (https://github.com/nibbles83/Linda) this contains the status-all command to generate the masternode info. Its also likely that future versions of the Official Linda wallet will include this command as well.
