### ISSUE TITLE
error Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by cryptonana** [nibbles83/LindaExplorer#2]
hello i try setup but i see error
i run this 
npm install --production after see this

npm WARN Failed to parse json
npm WARN Unexpected token 'x' at 33:6
npm WARN     "xml2js": "^0.4.19"
npm WARN      ^
npm WARN File: /root/LindaExplorer/package.json
npm WARN LindaExplorer No description
npm WARN LindaExplorer No repository field.
npm WARN LindaExplorer No README data
npm WARN LindaExplorer No license field.

i try manualy install xml2js and after run npm start i see this error

Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/LindaExplorer/lib/explorer.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/LindaExplorer/lib/database.js:14:11)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)

please some one resolve this issue

**Comment by nibbles83** [comment]
This issue should now be fixed with the latest commit.
Thanks
